// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxtovpnpvxxcpnzuxsqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4dG92cG5wdnh4Y3BuenV4c3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDYxMDUsImV4cCI6MjA1NzcyMjEwNX0.SqLVByAqr2LdcNdLgXIAQKh1lwRMi5FORgTa4PnN9FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);